name: tappeando
description: Tappeando app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.22.1
  http: ^0.12.0+2
  sqflite: ^1.1.6
  path_provider: ^1.2.0
  google_maps_flutter: ^0.5.19+2
  image_picker: ^0.6.1
  firebase_core: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/